# NumPy biblioteka

**NumPy** je Python biblioteka koja se koristi za naučna izračunavanja. Njome je definisan rad sa višedimenzionalnim nizovima, kao i brojnim matematičkim operacijama koje se mogu primeniti nad njima. Samo čuvanje podataka i izvršavanje operacija je optimizovano kako bi programi bili što efikasniji i brži. Na [ovom](http://www.numpy.org/) linku se nalazi zvanična stranica biblioteke sa mnogim korisnim informacijama, a [ovde](https://docs.scipy.org/doc/numpy/user/quickstart.html) se može pronaći koristan uvodni tutorijal. 

In [1]:
import numpy as np

Sledeći zadaci ilustruju neke od mogućnosti NumPy bibloteke.

Prvo ćemo kreirati i ispisati matricu $M$ dimenzije $2 \times 3$ koja sadrži brojeve od 1 do 6.

In [2]:
M = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
M

array([[1, 2, 3],
       [4, 5, 6]])

Za predstavljanje višedimenzionih nizova se koristi specifični tip `ndarray` (skraćenica od *n-dimensional array*).

In [4]:
type(M)

numpy.ndarray

U vezi sa nekom matricom (ali i svim drugim višedimenzionim nizovima) nas mogu zanimati broj dimenzija, njihove vrednosti, ukupan broj elemenata, kao i tip samih elemenata matrice. Za dobijanje ovih vrednosti se koriste, redom, svojstva `ndim`, `shape`, `size` i `dtype`.

In [5]:
print('Broj dimenzija matrice: ', M.ndim)

Broj dimenzija matrice:  2


Broj dva odgovara našim očekivanjima jer imamo vrste i kolone matrice. 

In [6]:
print('Vrednosti dimenzija matrice: ', M.shape)

Vrednosti dimenzija matrice:  (2, 3)


Dimenzije matrice se uvek prikazuju u formi uređenog para. 

In [7]:
print('Ukupan broj elemenata matrice: ', M.size)

Ukupan broj elemenata matrice:  6


In [8]:
print('Tip elemenata matrice: ', M.dtype)

Tip elemenata matrice:  int64


Svi elementi matrice moraju biti istog tipa i podrazumevano se tip elemenata matrice prilagođava vrednostima elemenata. Ukoliko želimo da prilikom kreiranja matrice eksplicitno naglasimo kog tipa su elementi, možemo navesti parametar `dtype`.

In [9]:
M = np.array([[1, 2, 3], [4, 5, 6]], dtype='int64')

NumPy paket podržava podrazumevane tipove kao što su `int_`, `float_`, `bool_` i `complex_`, ali nudi mogućnost rada i sa tipovima drugačijih opsega i preciznosti poput `int8`, `int16`, `uint8`, `float32`, `float64`, `complex128`, i slično. Umesto navođenja imena tipova mogu se koristiti i predefinisani tipovi NumPy paketa kao što su `np.int8`, `np.int16`, `np.float64` i slično.

In [10]:
M = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)

Informacije o memorijskom rasporedu elemenata, kao i o svojstvima fizičkog bloka memorije koji se koristi za čuvanje elemenata se može dobiti korišćenjem svojstva `flags`.

In [11]:
M.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

Svojstvo `C_CONTIGUOUS` označava da se vrste matrice ređaju u memoriji jedna za drugom (C u imenu svojstva naglasava da je ovo ponašanje nalik ponašanju u jeziku C). Sa druge strane, svojstvo `F_CONTIGUOUS` ukazuje na to da su kolone matrice postavljene u memoriji jedna za drugom (F u imenu svojstva ukazuje na sličnost sa programskim jezikom Fortran). Raspored elemenata je važan za izvođenje operacija na niskom nivou. 

Na primer, pogledajmo kako se ponaša operacija transponovanja matrice `transpose()` i novodobijena matrica `M_transposed`.

In [12]:
M_transposed = M.transpose()

In [13]:
M_transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
M_transposed.shape

(3, 2)

In [15]:
M_transposed.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

Primetimo da je matrica `M_transposed` kopija matrice `M` (na to ukazuje svojstvo `OWNDATA`) u kojoj su kolone te koje su smeštene jedna za drugom u memoriji. Zato se izvođenje operacije transponovanja zapravo svodi na ažuriranje svojstava memorijskog bloka. 

Kreirajmo dalje jedan vektor vrednosti koji sadrži brojeve od 0 do 11 i ispišimo njegova svojstva. 

In [16]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
print('Broj dimenzija vektora: ', a.ndim)

Broj dimenzija vektora:  1


In [19]:
print('Vrednost dimenzije vektora: ', a.shape)

Vrednost dimenzije vektora:  (12,)


In [20]:
print('Ukupan broj elemenata vektora: ', a.size)

Ukupan broj elemenata vektora:  12


In [21]:
print('Tip elemenata vektora: ', a.dtype)

Tip elemenata vektora:  int64


Zanimljivo je prikazati i svojstva vektora - sada su obe vrednosti `C_CONTIGUOUS` i `F_CONTIGUOUS` postavljene na vrednost `True`.

In [22]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

O nizovima biblioteke NumPy se može razmišljati i kao memorijskim baferima koji mogu imati drugačiji pogled. Na primer, nad baferom koji sadrži elemente vektora `a` se može kreirati matrica dimenzija `2x6` ili `3x4`. Za promenu pogleda se koristi funkcija `reshape()`. 

In [23]:
a_26 = a.reshape((2, 6))

In [24]:
a_26

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
a_34 = a.reshape((3, 4))

In [26]:
a_34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Navođenje nekompatibilnih dimenzija dovodi do greške.

In [27]:
a.reshape((2, 3))

ValueError: cannot reshape array of size 12 into shape (2,3)

Prethodni pozivi `reshape` funkcije su ekvivalentni pozivima `a.reshape((2, -1))` i `a.reshape((3, -1))`: broj `-1` koji se pojavljuje ukazuje na to da Python interpreter sam treba da izračuna nedostajuću dimenziju na osnovu poznate. Zato smo mogli napisati i  `a.reshape((-1, 6))` i `a.reshape((-1, 4))`.

In [29]:
a.reshape((2, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [30]:
a.reshape((-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

![reshape vizualizacija](assets/reshape.png)

Prilikom poziva `reshape` funkcije dimenzije novog bloka se mogu zadavati i pojedinačno. 

In [31]:
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Primetimo da su dimenzije obeležene sa `(12, )` i `(12, 1)` različite. Prva ukazuje na vektor sa 12 elemenata, a druga na matricu sa 12 vrsta i jednom kolonom. O ovome treba voditi računa prilikom izvođenja operacija jer se mogu dobiti neočekivani rezultati.

Slika ![shape_vector](assets/shape_vector.png) ukazuje na memorijsku organizaciju za vektor oblika `(12, )`, a slika ![shape_matrix](assets/shape_matrix.png) na memorijsku organizaciju za matricu oblika `(12, 1)`. Kao što možemo primetiti, razlika je jedino u broju indeksa koji se uporedo održavaju.

Prilikom očitavanja vrednosti elemenata indeksi koji se održavaju koriste vrednosti svojstva `strides` matrice. 

Matrica `M` je dimenzija `2x3` i sadrži elemente koji su tipa `int64` za čije je skladištenje potrebno po 8 bajtova. Za čitanje elementa u novoj vrsti potreban je pomeraj od 3x8 = 24 bajta, dok je za čitanje elementa u novoj koloni potreban pomeraj veličine 1x8 = 8 bajtova.

In [33]:
M.strides

(24, 8)

Vektor `a` takođe sadrži elemente koji su tipa `int64`, a da bi se pročitala sledeća vrednost potreban je pomeraj veličine 1x8=8 bajtova. 

In [34]:
a.strides

(8,)

Ukoliko je od vektora oblika `(12, )` potrebno kreirati matricu oblika `(12, 1)`, može se iskoristiti funkcija `reshape`. 

In [35]:
a.shape

(12,)

In [36]:
a_transformed = a.reshape(12, 1).shape

In [37]:
a_transformed

(12, 1)

Alternativa je dodavanje nove dimenzije pomoću `newaxis`. 

In [38]:
a_transformed = a[..., np.newaxis].shape

In [39]:
a_transformed

(12, 1)

Ukoliko je od višedimenzionog niza potrebno kreirati vektor vrednosti, osim funkcije `reshape` može se iskoristiti i funkcija `flatten`. 

In [40]:
M.flatten()

array([1, 2, 3, 4, 5, 6])

Nakon ovog tehničkog ali važnog uvoda koji se tiče načina na koji se višedimenzioni nizovi zapisuju u memoriji, prelazimo na pristup elementima nizova i izdvajanje odgovarajućih elemenata matrice. Zajedno se za ove radnje koristi odrednica *indeksiranje i isecanje* (engl. indexing and slicing). ![indexing and slcing](assets/indexing_and_slicing.png) 

Da bismo očitali željene vrednosti, potrebno je da navedemo odgovarajuće indekse. Numeracija pozicija, očekivano, počinje nulom.

Element na poziciji (0, 1) matrice M možemo očitati sa:

In [41]:
M[0, 1]

2

Slično, peti element vektora a možemo očitati sa:

In [42]:
a[4]

4

Pristup nepostojećim elementima rezultira greškom tipa `IndexError`.

In [43]:
M[2, 2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [44]:
a[15]

IndexError: index 15 is out of bounds for axis 0 with size 12

Kreiraćemo sada nešto veću matricu $S = \begin{bmatrix}1&2&3&4&5\\6&7&8&9&10\\11&12&13&14&15\end{bmatrix}$ na kojoj možemo da demonstriramo još neke tehnike pristupa elementima.

In [45]:
S = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

In [46]:
S

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

Elementi koji pripadaju prvoj koloni se mogu pročitati sa: 

In [47]:
S[:, 1]

array([ 2,  7, 12])

Elementi koji pripadaju poslednjoj koloni se mogu pročitati sa:

In [48]:
S[:, -1]

array([ 5, 10, 15])

Kolone matrice počevši od prve se mogu pročitati sa:

In [49]:
S[:, 1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

Kolone matrice počevši od prve do treće se mogu pročitati sa:

In [50]:
S[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

Obratiti pažnju da se prilikom navođenja opsega druga vrednost ne uzima inkluzivno.

Izdvajanje svih parnih kolona (sa indeksima 0, 2 i 4) se može postići sa:

In [51]:
S[:, ::2]

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

Slično se odnosi i na vrste matrice. Na primer, elementi koji pripadaju prvoj vrsti se mogu pročitati sa: 

In [52]:
S[1, :]

array([ 6,  7,  8,  9, 10])

Izdvajanje svakog drugog elementa vrste i kolone se može postići sa:

In [53]:
S[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

Kvadratna podmatrica reda 2 u donjem desnom uglu se može izdvojiti fragmentom koda:

In [54]:
S[-2:,-2:]

array([[ 9, 10],
       [14, 15]])

Ukoliko je istovremeno potrebno pročitati veći broj vrednosti sa određenih pozicija, dozvoljeno je kombinovanje indeksa. Na primer, sledećim kodom se izdvajaju elementi na pozicijama (1, 1), (1, 3) i (2, 4).

In [55]:
S[(1, 1, 2), (1, 3, 4)]

array([ 7,  9, 15])

Za izdvajanje elemenata mogu se koristiti i logičke maske. Posmatrajmo matricu $mask$:

In [56]:
mask = np.array([[False, False, False, False, False],
                 [True, True, True, True, True],
                 [True, True, False, False, False]])

Konstrukcija `S[mask]` će izdvojiti one elemente koji se nalaze na pozicijama obeleženim sa `True`.

In [57]:
S[mask]

array([ 6,  7,  8,  9, 10, 11, 12])

Često su potrebni nizovi koji su specifične forme.

Niz koji sadrži elemente iz intervala određenog početnom i krajnjom tačkom sa odgovarajućim korakom se može dobiti funkcijom `arrange`. Ovu funkciju ćemo baš često koristiti.

Na primer, niz koji sadrži sve parne brojeve iz intervala [0, 10) možemo dobiti sledećim pozivom:

In [58]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

Niz koji sadrži vrednosti ekvidistantne mreže određene početnom i krajnom tačkom možemo dobiti korišćenjem funkcije `linspace`.

Na primer, 5 tačaka ekvidistantne mreže intervala [0, 1] (desna granica je uključena!) možemo dobiti sledećim pozivom:

In [59]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Višedimenzioni niz nula možemo dobiti korišćenjem funkcije `zeros`.

In [60]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Višedimenzioni niz jedinica možemo dobiti korišćenjem funkcije `ones`.

In [61]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Jediničnu matricu zadate dimenzije možemo dobiti pozivom funkcije `eye`.

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Dijagonalnu matricu sa željenim elementima duž glavne dijagonale možemo dobiti korišćenjem funkcije `diag`. Na primer, matricu koja na glavnoj dijagonali ima elemente 4, 3, 2 i 1 možemo dobiti na sledeći način:

In [63]:
np.diag([4, 3, 2, 1])

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

Ze generisanje slučajnih brojeva brojeva mogu se koristiti funkcije `random` paketa biblioteke `numpy`. Praksa je da se zbog mogućnosti reprodukovanja eksperimenta uvek pre korišćenja ovih funkcija podesi vrednost koja se zove `seed`, a kojom se utiče na algoritam generisanja vrednosti.

In [64]:
np.random.seed(7)

Funkciju `uniform` možemo koristiti za generisanje brojeva sa uniformnom raspodelom. Na primer, 5 brojeva iz uniformne raspodele intervala [2, 5) možemo dobiti pozivom:

In [65]:
np.random.uniform(2, 5, 5)

array([2.22892487, 4.33975638, 3.31522769, 4.17039553, 4.93396854])

Ukoliko je potrebno da generišemo matricu vrednosti, na primer dimenzija 5x5, dovoljno je da vrednost trećeg parametra (parametar `size`) postavimo na odgovarajuću dimenziju:

In [66]:
np.random.uniform(2, 5, (5,5))

array([[3.61548761, 3.50336139, 2.2161534 , 2.80531694, 3.4996475 ],
       [4.03768999, 4.41121711, 3.1428234 , 2.19780904, 2.8644368 ],
       [4.72878058, 2.64015606, 3.35637189, 4.79361806, 2.07469768],
       [3.80164675, 4.8503885 , 2.69090864, 3.64546976, 4.72738512],
       [2.39950834, 3.57023774, 4.25122958, 4.00703972, 3.40325858]])

Funkciju `randn` možemo koristiti za generisanje brojeva iz standardne $N(0, 1)$ normalne raspodele tj. normalne raspodele sa nultom sredinom i jediničnom standardnom devijacijom.

Na primer, matricu dimenzija 4x3 iz $N(0, 1)$ raspodele možemo generisati sa:

In [67]:
np.random.randn(4, 3)

array([[-0.04538603, -1.4506787 , -0.40522786],
       [-2.2883151 ,  1.04939655, -0.41647432],
       [-0.74255353,  1.07247013, -1.65107559],
       [ 0.53542936, -2.0644148 , -0.66215934]])

Za generisanje proizvoljne vrednosti iz normalne raspodele $N(\mu, \sigma^2)$ može se koristiti izraz `sigma * np.random.randn(...) + mu` ili funkcija `np.random.normal(...)` sa parametrima $\mu$ i $\sigma$.

Na primer, matricu dimenzija 4x3 iz $N(3, 2^2)$ raspodele možemo generisati sa:

In [68]:
np.random.normal(3, 4, (4, 3))

array([[-1.81687938e+00,  8.84790251e+00,  1.00646435e+01],
       [ 1.68234499e+00,  6.36293297e+00,  2.28005439e+00],
       [ 5.27224755e+00, -1.13487857e-02, -3.83335681e+00],
       [-4.21239463e+00,  4.53248741e+00,  1.19903802e+01]])

Nadalje ćemo upoznati matrične operacije.

Kreiraćemo matrice $M_1=\begin{bmatrix}1&3&5\\7&9&11\\13&15&17\end{bmatrix}$ i $M_2=\begin{bmatrix}2&4&6\\8&10&12\\14&16&18\end{bmatrix}$.

In [69]:
M1 = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17]])
M2 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])

Zbir matrica $M_1$ i $M_2$ možemo dobiti korišćenjem operatora `+` ili funkcije `add`. 

In [70]:
M1 + M2

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [71]:
np.add(M1, M2)

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

Pokoordinatno množenje matrica $M_1$ i $M_2$ se može realizovati korišćenjem operatora `*` ili funkcije `multiply`.

In [72]:
M1 * M2

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [73]:
np.multiply(M1, M2)

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

Matrično množenje se može realizovati korišćenjem funkcije `dot`. 

In [74]:
np.dot(M1, M2)

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

Prilikom izvođenja gornjih operacija treba voditi računa o dimenzijama matrica.`Broadcasting` je termin kojim se opisuje ponašanje Python interpretera kojim pokušava sa svođenjem na iste dimenzije dva ili više višedimenzionih nizova. Ovo se posebno odnosi na vektore koji imaju različite oblike (svojstvo `shape`) pa izvođenje nekih operacija umesto očekivane greške može rezultirati neočekivanim rezultatom.

![broadcasting](assets/broadcasting.png)

Tako je, na primer, moguće višedimenzionim nizovima dodavati skalare ili ih množiti skalarima. Ove operacije su ekvivalentne pokoordinatnim sabiranjima tj. množenjima.

In [75]:
v = np.array([1, 2, 3, 4])

In [76]:
# ekvivalent operacije: a + np.array([5, 5, 5, 5])
v + 5

array([6, 7, 8, 9])

In [77]:
A = np.array([[2, 3, 0], [0, 0, 4]])

In [78]:
A

array([[2, 3, 0],
       [0, 0, 4]])

In [79]:
# ekvivalent operacije: np.array([[5, 5, 5], [5, 5, 5]]) * A
5 * A

array([[10, 15,  0],
       [ 0,  0, 20]])

Moguće je sabirati matrice i vektore kompatibilnih dimenzija. Na primer, moguće je izvršavati sabiranje matrice dimenzije $n \times m$ i vektora koji sadrži $m$ elemenata. 

In [80]:
A = np.array([[2, 3, 0], [0, 0, 4]])

In [81]:
v = np.array([1, 2, 3])

In [82]:
# ekvivalent operacije A + np.array([[1, 2, 3], [1, 2, 3]])
A + v

array([[3, 5, 3],
       [1, 2, 7]])

In [83]:
# ekvivalent operacije np.array([[1, 2, 3], [1, 2, 3]]) + A
v + A

array([[3, 5, 3],
       [1, 2, 7]])

Evo još jednog neobičnog primera: 

In [84]:
u1 = np.ones((3, 1))

In [85]:
u1.shape

(3, 1)

In [86]:
u2 = np.array([4, 5, 6, 7])

In [87]:
u2.shape

(4,)

In [88]:
u1 + u2

array([[5., 6., 7., 8.],
       [5., 6., 7., 8.],
       [5., 6., 7., 8.]])

Nad višedimenzionim nizovima se mogu primenjivati i matematičke funkcije poput sinusa, kosinusa, eksponenta i slično. U ovim slučajevima se funkcije primenjuju pokoordinatno, tj. nad svakim elementom matrice pojedinačno.

In [89]:
np.sin(M1)

array([[ 0.84147098,  0.14112001, -0.95892427],
       [ 0.6569866 ,  0.41211849, -0.99999021],
       [ 0.42016704,  0.65028784, -0.96139749]])

In [90]:
np.exp(M2)

array([[7.38905610e+00, 5.45981500e+01, 4.03428793e+02],
       [2.98095799e+03, 2.20264658e+04, 1.62754791e+05],
       [1.20260428e+06, 8.88611052e+06, 6.56599691e+07]])

Na raspolaganju su i funkcije za sumiranje vrednosti (funkcija `sum`), pronalaženje maksimuma (funkcija `max`), minimuma (funkcija `min`) ili njihovih pozicija u višedimenzionom nizu (funkcije `argmin` i `argmax`). Sve ove funkcije uz niz očekuju i osu duž koje funkcija treba da se izvrši. Ukoliko se osa ne navede, funkcija se primenjuje nad svim elementima matrice. 

Da bismo demonstrirali rad ovih funkcija, kreiraćemo matricu dimenzije 4x3 koja sadrži nasumično odabranih 12 brojeva iz intervala [0, 100). Za generisanje ove matrice iskoritićemo funkciju `randint` paketa `random`.

In [91]:
M = np.random.randint(0, 100, 12).reshape(4, 3)

In [92]:
M

array([[58, 47, 16],
       [12, 93,  9],
       [76, 67, 14],
       [20, 53, 15]])

Suma svih elemenata matrice je: 

In [93]:
np.sum(M)

480

Suma po kolonama se može dobiti postavljanjem ose na vrednost 0, a suma po vrstama postavljanjem na vrednost 1.

In [94]:
np.sum(M, axis=0)

array([166, 260,  54])

In [95]:
np.sum(M, axis=1)

array([121, 114, 157,  88])

Najveća vrednost matrice i pozicija na kojoj se ona nalazi su: 

In [96]:
np.max(M)

93

In [97]:
np.argmax(M)

4

Vrednost koja predstavlja poziciju je u skladu sa rasporedom elemenata u memoriji. 

Prosečna vrednost niza se izračunava korišćenjem funkcije `average`. 

In [98]:
np.average(M)

40.0

Nekada je na osnovu postojećih višedimenzionih nizova potrebno kreirati novi niz.

Kreiraćemo nizove $x = [1, 2, 3]$ i $y = [5, 6, 7]$:

In [99]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

Vertikalno nadovezivanje nizova možemo postići korišćenjem funkcije `vstack`:

In [101]:
np.vstack((x, y))

array([[1, 2, 3],
       [4, 5, 6]])

Horizontalno nadovezivanje nizova možemo postići korišćenjem funkcije `hstack`:

In [102]:
np.hstack((x, y))

array([1, 2, 3, 4, 5, 6])

Prilikom operacije dodele jednog višedimenzionog niza drugom nizu, ne vrši se fizičko kopiranje memorije, već se deli alocirani memorijski blok. 

Kreirajmo matricu $A=\begin{bmatrix}1&2&3\\4&5&6\end{bmatrix}$ i dodelimo je matrici $B$.

In [103]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = A

In [104]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
B

array([[1, 2, 3],
       [4, 5, 6]])

Promena vrednosti matrice B se odražava na matricu A i obrnuto, promena vrednosti matrice A se odražava na matricu B.

In [106]:
B[0, 0] = 10

In [107]:
B

array([[10,  2,  3],
       [ 4,  5,  6]])

In [108]:
A

array([[10,  2,  3],
       [ 4,  5,  6]])

Ukoliko je potrebno napraviti fizičku kopiju matrice, može se koristiti funkcija `copy`.

In [109]:
C = np.copy(A)

In [110]:
C

array([[10,  2,  3],
       [ 4,  5,  6]])

Sada promene matrice $C$ ne utiču na matricu $A$.

In [111]:
C[0,0] = 100

In [112]:
C

array([[100,   2,   3],
       [  4,   5,   6]])

In [113]:
A

array([[10,  2,  3],
       [ 4,  5,  6]])

Da li dve matrice dele memorijski blok može se proveriti korišćenjem funkcije `shares_memory`:

In [114]:
np.shares_memory(A, C)

False

In [115]:
np.shares_memory(A, B)

True

Da li dve matrice imaju jednake elemente može se proveriti korišćenjem funkcija `array_equal` ili koriščenjem operatora `==`:

In [116]:
np.array_equal(A, B)

True

In [117]:
np.array_equal(A, C)

False

In [118]:
A == C

array([[False,  True,  True],
       [ True,  True,  True]])

Prilikom korišćenja operatora `==` vrši se pokoordinatno poređenje pa se dodatno mora proveriti da li su u rezultujućem nizu sve vrednosti jednake `True`. U tome nam može pomoći funkcija `all_true`.

In [121]:
np.alltrue(A == C)

False

In [122]:
np.alltrue(A == B)

True

### Zadaci za vežbu: 

1. Kreirati dva vektora $x$ i $y$ koji sadrže po 10 nasumično odabranih celih brojeva iz intervala [0, 10), a potom izračunati njiihov skalarni proizvod.

2. Za matricu $M = \begin{bmatrix}1&2&3\\4&5&6\end{bmatrix}$ i vektor $x = [10, 20, 30]$ izračunati $M+x$. 

3. Kreirati matricu dimenzija 4x4 koja sadrži vrednosti od 0 do 15, a potom odrediti sumu onih elemenata matrice koji su veći od njenog proseka.

4. Konstruisati matricu dimenzije 4x4 koja na sporednoj dijagonali ima redom elemente 4, 3, 2 i 1, a na ostalim pozicijama nule.