# Rad sa matricama

Kao što smo videli, višedimenzioni nizovi predstavljaju osnovnu strukturu podataka `numpy` paketa. Paket `numpy.linalg` specifično podržava razne algebarske funkcionalnosti u radu sa matricama, među kojima su nalaženje determinante matrice, njenog inverza, sopstvenih vektora i sopstvenih vrednosti, normi, uslovljenosti i drugih.  

In [1]:
import numpy as np
from numpy import linalg as LA

Za demonstraciju funkcija `numpy.linalg` paketa, kreiraćemo kvadratnu matricu 
$A = \begin{bmatrix}
    1 & 2 & 4 \\
    -5 & 7 & 2 \\
    5 & 1 & 9
\end{bmatrix}$.

In [2]:
A = np.array([[1, 2, 4], [-5, 7, 2], [5, 1, 9]])

In [3]:
A

array([[ 1,  2,  4],
       [-5,  7,  2],
       [ 5,  1,  9]])

`Determinanta` matrice se može definisati rekurzivno. Tako za matrice reda $2 \times 2$, $3 \times 3$ i $4 \times 4$, važi 

* $\begin{vmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{vmatrix} = a_{11}a_{22}-a_{12}a_{21},$
* $\begin{vmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{vmatrix} = a_{11}\begin{vmatrix}a_{22}&a_{23}\\a_{32}&a_{33}\end{vmatrix} - a_{12}\begin{vmatrix}a_{21}&a_{23}\\a_{31}&a_{33}\end{vmatrix} + a_{13}\begin{vmatrix}a_{21}&a_{22}\\a_{31}&a_{32}\end{vmatrix},$ 
* $\begin{vmatrix}a_{11}&a_{12}&a_{13}&a_{14}\\a_{21}&a_{22}&a_{23}&a_{24}\\a_{31}&a_{32}&a_{33}&a_{34}\\a_{41}&a_{42}&a_{43}&a_{44}\end{vmatrix} = a_{11} \begin{vmatrix}a_{22}&a_{23}&a_{24}\\a_{32}&a_{33}&a_{34}\\a_{42}&a_{43}&a_{44}\end{vmatrix} - a_{12} \begin{vmatrix}a_{21}&a_{23}&a_{24}\\a_{31}&a_{33}&a_{34}\\a_{41}&a_{43}&a_{44}\end{vmatrix} + a_{13}
\begin{vmatrix}a_{21}&a_{22}&a_{24}\\a_{31}&a_{32}&a_{34}\\a_{41}&a_{42}&a_{44}\end{vmatrix} - a_{14} \begin{vmatrix}a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\a_{41}&a_{42}&a_{43}\end{vmatrix}.$

Svaki sabirak u izrazu za izračunavanje determinante predstavlja proizvod jednog elementa matrice i determinante matrice koja se dobija od polazne uklanjanjem reda i kolone kojima pripada taj element. Za razlaganje se mogu odabrati svi elementi proizvoljne vrste ili kolone. U našem slučaju su uzeti elementi prve vrste. Svaki drugi sabirak u izrazu treba da bude pomnožen sa $-1$. 

Ova definicija se lako može uopštiti i na matrice većeg reda.

Za računanje determinante matrice koristimo funkciju `det`:

In [4]:
print('Determinanta matrice:', LA.det(A))

Determinanta matrice: 10.999999999999972


Ukoliko je determinanta kvadratne matrice $A$ različita od nule, postoji njen `inverz` tj. matrica $A^{-1}$ za koji važi $AA^{-1}=I$, gde je $I$ jedinična matrica.

Za računanje inverza matrice koristimo funkciju `inv`:

In [5]:
print('Inverz matrice:')
print(LA.inv(A))

Inverz matrice:
[[ 5.54545455 -1.27272727 -2.18181818]
 [ 5.         -1.         -2.        ]
 [-3.63636364  0.81818182  1.54545455]]


Za matrice čija je determinanta jednaka nuli kažemo da su `singularne` matrice.

Ako za neki realan vektor $x$ važi $Ax = \lambda x$, gde je $\lambda$ skalar, vektor $x$ se naziva `sopstveni vektor`, a $\lambda$ `sopstvena vrednost` matrice $A$. 

U opštem slučaju sopstvene vrednosti se dobijaju kao nule jednačine $det(A-\lambda I)=0$. Nešto kasnije na kursu ćemo upoznati metode stepenovanja i iscrpljivanja za dobijanje sopstvenih vrednosti. Na nivou biblioteke nam je na raspolaganju funkcija `eig` koja izračunava sopstvene vrednosti i normirane sopstvene vektore. 

In [6]:
values, vectors = LA.eig(A)
print('Sopstvene vrednosti date u nizu:')
print(values)
print('Sopstveni vektori dati kao kolone matrice:')
print(vectors)

Sopstvene vrednosti date u nizu:
[ 0.17157288  5.82842712 11.        ]
Sopstveni vektori dati kao kolone matrice:
[[ 6.57393413e-01 -6.10635274e-02  3.71390676e-01]
 [ 6.10673901e-01 -9.20292562e-01  7.22840190e-16]
 [-4.41487584e-01  3.86436083e-01  9.28476691e-01]]


**Norma** matrice $A$ je nenegativan broj $||A||$ za koji važi: 

* $||A|| = 0$ ako i samo ako je $A = 0$,
* $||kA|| = |k|\cdot||A||$, za $k$ koje pripada prostoru skalara
* $||A+B||\le||A||+||B||$,
* $||AB||\le||A||\cdot||B||$. 

Među najpoznatijim normama su matrična `1-norma`, matrična `2-norma`, matrična $\infty$`-norma` i `Frobeniusova` norma.

* **Matrična 1-norma** predstavlja maksimalni zbir sume apsolutnih vrednosti elemenata u svakoj koloni i definisana je sa $||A||_1 = \max_j \sum_i |a_{ij}|$.

* **Matrična 2-norma** je jednaka korenu najveće sopstvene vrednosti matrice $A^TA$ i dedinisana je sa $||A||_2 = \sqrt{\lambda_{max} (A^TA)}$. U slučaju kompleksne matrice, umesto transponovane, koristi se [konjugovana transponovana matrica](http://mathworld.wolfram.com/ConjugateTranspose.html).

* **Frobeniusova norma** predstavlja koren sume apsolutnih vrednosti svih elemenata matrice i definisana je sa $||A||_F = \sqrt{\sum_i \sum_j |a_{ij}|^2}$. Važi $||A||_2 \le ||A||_F \le \sqrt{r} \cdot ||A||_2$, gde je $r$ rang matrice $A$.

* **Matrična $\infty$-norma** predstavlja maksimalni zbir sume apsolutnih vrednosti elemenata u svakom redu i definisana je sa $||A||_{\infty} = \max_i \sum_j |a_{ij}|$.

Za računanje norme koristićemo funkciju `norm`, a njenim parametrom `ord` naglašavaćemo o kojoj normi je reč.

In [7]:
norm1 = LA.norm(A, ord = 1)
norm2 = LA.norm(A, ord = 2)
normf = LA.norm(A, ord = 'fro')
norminf = LA.norm(A, ord = np.inf)

print('Matricna 1-norma:', norm1)
print('Matricna 2-norma:', norm2)
print('Frobeniusova norma:', normf)
print('Matricna beskonacna norma:', norminf)

Matricna 1-norma: 15.0
Matricna 2-norma: 11.21324242009752
Frobeniusova norma: 14.352700094407323
Matricna beskonacna norma: 15.0


U prostoru konačne dimenzije ($R^n$ ili $R^{nxm}$ su slučajevi koje razmatramo) sve norme su međusobno ekvivalentne. To znači da za dve norme $\|\|_{n1}$ i $\|\|_{n2}$ postoje pozitivne realne konstante $c_1$ i $c_2$ takve da je $c_1\cdot\|x\|_{n1}\leq \|x\|_{n2} \leq c_2\cdot\|x\|_{n1}$  

`Kondicioni broj` $\kappa(A)$ kvadratne invertibilne matrice $A$ je numerička vrednost koja se definiše sa $\kappa(A) = ||A||\cdot||A^{-1}||$. Ukoliko matrica $A$ nije invirtibilna, tada je $\kappa(A) = \infty$. 

Za računanje kondicionog broja koristićemo funkciju `cond`.

In [8]:
print('Kondicioni broj:', LA.cond(A))

Kondicioni broj: 102.39895228883073


In [9]:
print('Kondicioni broj: ', LA.norm(A, ord = 2) * LA.norm(LA.inv(A), ord = 2))

Kondicioni broj:  102.39895228883104


Kondicioni broj zavisi od vrste norme matrice. Podrazumevano se koristi matrična 2-norma.

Praktično, kondicioni broj ukazuje na numeričku stabilnost sistema u kojima matrica figuriše. Za sistem jednačina $Ax=b$, vrednost $\kappa(A)$ određuje promenu vrednosti vektora $x$ u zavisnosti od promene vrednosti vektora $b$. Ukoliko je vrednost $\kappa(A)$ velika, tada i male promene vrednosti vektora $b$ utiču da se vrednost vektora $x$ dosta promeni. Ako je vrednost kondicionog broja mala, onda promena vektora $x$ neće biti naročito velika.

Ilustrujmo to primerom 
$\begin{bmatrix}
    1 & 2 \\
    2 & 3.999
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2
\end{bmatrix}
=
\begin{bmatrix}
4 \\
7.999
\end{bmatrix}
$

In [10]:
A = np.array([[1, 2], [2, 3.999]])
b = np.array([4, 7.999]).T

Rešenje polaznog sistema je: 

In [11]:
x = LA.inv(A).dot(b)

In [12]:
x

array([2., 1.])

Male promene u vrednostima vektora $b$ dovode do velikih promena rešenja:

In [13]:
A1 = A.copy() 
b1 = b.copy() 
b1[0] =  b1[0] + 0.001 
b1[1] =  b1[1] - 0.001 

In [14]:
x1 = LA.inv(A1).dot(b1)

In [15]:
x1

array([-3.999,  4.   ])

Ovakvo ponašanje možemo objasniti uslovljenošću matrice $A$:

In [16]:
LA.cond(A)

24992.000960058016

Takođe, male promene vrednosti matrice $A$ dovode do velikih promena u rešenju:

In [17]:
A2 = A.copy() 
A2[0, 0] += 0.001
A2[0, 1] += 0.001
A2[1, 0] += 0.001
A2[1, 1] -= 0.001
b2 = b.copy() 

In [18]:
x2 = LA.inv(A2).dot(b2)

In [19]:
x2

array([ 6.98901648, -1.49725412])

Možemo prokomentarisati da se uslovljenost matrice ne dovodi nužno u vezu sa njenom determinantom. Matrice $k \cdot A$ je primer matrice čija je uslovljenost konstantna $cond(kA)=||kA||\cdot||(kA)^{-1}|| = k||A||\cdot \frac{1}{k}||A||^{-1}=||A||||A^{-1}||=cond(A)$, a čija se determinanta, u zavisnosti od vrednosti konstante $k$ može učiniti proizvoljno malom ili proizvoljno velikom jer je $det(kA)=k\cdot det(A)$.

### Zadatak za vežbu:

Hilbertova matrica reda $n$ je matrica čiji su elementi oblika $A_{i, j} = \frac{1}{i+j-1}$ za i, j = 1, 2, 3, ...  Primer Hilbertove matrice reda 3 je $
\begin{bmatrix}
1 & \frac{1}{2} & \frac{1}{3} \\
\frac{1}{2} & \frac{1}{3} & \frac{1}{4} \\
\frac{1}{3} & \frac{1}{4} & \frac{1}{5} \\
\end{bmatrix}
$.

a) Napisati funkciju koja generiše Hilbertovu matricu reda $n$.

b) Napisati funkciju koja za date parametre $n$ i $\sigma$ generiše vektor $b$ čiji su elementi određeni sa $$b_i = \sum_{j=1}^{j=n}{\frac{1}{i+j-1}}+\sigma R(i)$$ u kojem $R(i)$ predstavlja slučajan broj iz intervala $[-1, 1]$.

c) Koristeći napisane funkcije koje genirišu matricu $H$ i vektor $b$ rešiti sistem jednačina $Hx=b$ za $n=10$ i $\sigma=10^{-14}$.

d) Koristeći napisane funkcije koje genirišu matricu $H$ i vektor $b$ rešiti sistem jednačina $Hx=b$ za $n=10$ i $\sigma=10^{-5}$.

e) Čime se može objasniti ovakvo ponašanje sistema? Odgovor obrazložiti.